# Generated by Django 5.2 on 2025-04-08 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_superutilisateur',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
