# Generated by Django 5.2 on 2025-04-12 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_utilisateur_est_superutilisateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='est_actif',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='est_staff',
            new_name='is_staff',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format: '44076356', '+(222)44076356' ou '+22244076356'.", regex='^(\\+?\\d{8,15}|\\(\\+?\\d{1,3}\\)\\d{7,14}|\\+\\d{1,3}\\d{7,14})$')], verbose_name='Numéro de téléphone'),
        ),
    ]
