# Generated by Django 5.2 on 2025-04-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_est_actif_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_verifie',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Compte vérifié et actif'),
        ),
    ]
