# Generated by Django 5.1.6 on 2025-04-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_utilisateur_est_verifie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='expiration_jeton_reinitialisation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du jeton de réinitialisation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='jeton_reinitialisation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Jeton de réinitialisation'),
        ),
    ]
