# Generated by Django 5.1.6 on 2025-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_utilisateur_expiration_jeton_reinitialisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='intitule_poste',
            field=models.CharField(blank=True, max_length=100, verbose_name='Intitulé de poste'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='specialisation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spécialisation principale'),
        ),
    ]
