# Generated by Django 5.1.6 on 2025-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_freelancer_intitule_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='intitule_poste',
            field=models.CharField(max_length=100, verbose_name='Intitulé de poste'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='specialisation',
            field=models.CharField(max_length=100, verbose_name='Spécialisation principale'),
        ),
    ]
