# Generated by Django 5.2 on 2025-05-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_evaluation_notification_projet_postulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='est_actif',
        ),
    ]
