# Generated by Django 5.2 on 2025-05-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_projet_est_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
