# Generated by Django 5.2 on 2025-05-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_projet_est_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='est_vue',
        ),
    ]
