# Generated by Django 5.2 on 2025-05-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_notification_options_notification_est_vue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='est_vue',
        ),
    ]
